version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./docker_bin:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
